### ISSUE TITLE
global_settings date string cfg_value is converted to datetime string automatically

### ISSUE THREAD

**Issue by joyeez** [joyeez/rc_backTest#19]
provisioning the configuration of start_dt/end_dt with the code : 
self.global_settings_add(testid, start_dt = '2014-01-01', end_dt = '2015-12-31')

while the global_settings table got the value 2014-01-01 00:00:00 and 2015-12-31 00:00:00. 

This lead to error while try to parsing the string to date .
DataProxy.py:51
start_dt = datetime.datetime.strptime(self.get_config_value('back_test_start_time'), '%Y-%m-%d')

The code above will raise error:

(Pdb) datetime.datetime.strptime(self.get_config_value('back_test_start_time'), '%Y-%m-%d')
*** ValueError: unconverted data remains:  00:00:00

**Comment by joyeez** [comment]
Keep date format or datetime format string both are OK,  following two comparing way work fine both:

MySQL [stk_cn]> select date_time from wsi_2014_03 where date_time between '2014-03-03' and '2014-03-04' limit 20;
+---------------------+
| date_time           |
+---------------------+
| 2014-03-03 09:25:00 |
| 2014-03-03 09:30:00 |
| 2014-03-03 09:31:00 |
| 2014-03-03 09:32:00 |


MySQL [stk_cn]> select date from wsd_2014 where date between '2014-03-03 00:00:00' and '2014-03-04 23:00:00' limit 10;
+------------+
| date       |
+------------+
| 2014-03-03 |
| 2014-03-04 |
| 2014-03-03 |
| 2014-03-04 |

**Comment by joyeez** [comment]
considering the code in SqlDbCenter.py,  the start_dt is supposed to be a datetime type instead of date type. So just modify the DataProxy.py : 51 to following:
start_dt = datetime.datetime.strptime(self.get_config_value('back_test_start_time'), '%Y-%m-%d %H:%M:%S')

**Comment by song-pj** [comment]
code fixed on main branch.
